/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.mastermind;

/**
 *
 * @author mlongton
 */
public class MasterMindSettingsDialog extends javax.swing.JDialog {

    public MMSettingsState chosenSettings;
    /**
     * Creates new form MasterMindSettingsDialog
     */
    public MasterMindSettingsDialog(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null);
    }
    
    public MasterMindSettingsDialog(java.awt.Frame parent, boolean modal, MMSettingsState initPrefs) {
        super(parent, modal);
        initComponents();
        chosenSettings = null;
        this.lengthSlider.setValue(initPrefs.length);
        if (initPrefs.autoGuess) {
            this.computerGuessRButton.doClick();
        }
        else {
            this.userGuessRButton.doClick();
        }
        switch (initPrefs.wordChooser) {
            case MMSettingsState.USER_WORD:
                this.userWordRButton.doClick();
                break;
            case MMSettingsState.RANDOM_WORD:
                this.randomWordRButton.doClick();
                break;
            case MMSettingsState.SECRET_WORD:
                this.secretWordRButton.doClick();
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wordChoiceButtonGroup = new javax.swing.ButtonGroup();
        guesserButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lengthSlider = new javax.swing.JSlider();
        lengthLabel = new javax.swing.JLabel();
        randomWordRButton = new javax.swing.JRadioButton();
        userWordRButton = new javax.swing.JRadioButton();
        secretWordRButton = new javax.swing.JRadioButton();
        userGuessRButton = new javax.swing.JRadioButton();
        computerGuessRButton = new javax.swing.JRadioButton();
        OKButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        info1 = new javax.swing.JLabel();
        info2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Number of Letters:");

        lengthSlider.setMaximum(8);
        lengthSlider.setMinimum(2);
        lengthSlider.setMinorTickSpacing(1);
        lengthSlider.setPaintTicks(true);
        lengthSlider.setSnapToTicks(true);
        lengthSlider.setValue(4);
        lengthSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lengthSliderStateChanged(evt);
            }
        });

        lengthLabel.setText("4");

        wordChoiceButtonGroup.add(randomWordRButton);
        randomWordRButton.setSelected(true);
        randomWordRButton.setText("Random Word");

        wordChoiceButtonGroup.add(userWordRButton);
        userWordRButton.setText("Enter a Word");
        userWordRButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                userWordRButtonStateChanged(evt);
            }
        });

        wordChoiceButtonGroup.add(secretWordRButton);
        secretWordRButton.setText("Enter Blacks and Whites");

        guesserButtonGroup.add(userGuessRButton);
        userGuessRButton.setSelected(true);
        userGuessRButton.setText("Enter Guesses");

        guesserButtonGroup.add(computerGuessRButton);
        computerGuessRButton.setText("Click for Auto-Guesses");

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        info1.setText("Who will pick the word?");

        info2.setText("Who will try to guess the word?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userGuessRButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(computerGuessRButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(randomWordRButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userWordRButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secretWordRButton)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OKButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lengthSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lengthLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info1)
                            .addComponent(info2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(info1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomWordRButton)
                    .addComponent(userWordRButton)
                    .addComponent(secretWordRButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(lengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthLabel))
                .addGap(18, 18, 18)
                .addComponent(info2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userGuessRButton)
                    .addComponent(computerGuessRButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lengthSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lengthSliderStateChanged
        lengthLabel.setText(String.valueOf(lengthSlider.getValue()));
    }//GEN-LAST:event_lengthSliderStateChanged

    private void userWordRButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_userWordRButtonStateChanged
        lengthSlider.setEnabled(!userWordRButton.isSelected());
        lengthLabel.setEnabled(!userWordRButton.isSelected());
    }//GEN-LAST:event_userWordRButtonStateChanged

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        boolean autoGuess = computerGuessRButton.isSelected();
        int chooser;
        if (userWordRButton.isSelected()) chooser = MMSettingsState.USER_WORD;
        else if (randomWordRButton.isSelected()) chooser = MMSettingsState.RANDOM_WORD;
        else chooser = MMSettingsState.SECRET_WORD;
        chosenSettings = new MMSettingsState(lengthSlider.getValue(), chooser, autoGuess);
        this.setVisible(false);
    }//GEN-LAST:event_OKButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterMindSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterMindSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterMindSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterMindSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MasterMindSettingsDialog dialog = new MasterMindSettingsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton computerGuessRButton;
    private javax.swing.ButtonGroup guesserButtonGroup;
    private javax.swing.JLabel info1;
    private javax.swing.JLabel info2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JSlider lengthSlider;
    private javax.swing.JRadioButton randomWordRButton;
    private javax.swing.JRadioButton secretWordRButton;
    private javax.swing.JRadioButton userGuessRButton;
    private javax.swing.JRadioButton userWordRButton;
    private javax.swing.ButtonGroup wordChoiceButtonGroup;
    // End of variables declaration//GEN-END:variables
}
