/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.mastermind;

/**
 *
 * @author mlongton
 */
public class MMPossibilityListCell extends javax.swing.JPanel {

    /**
     * Creates new form MMPossibilityListCell
     */
    public MMPossibilityListCell() {
        initComponents();
    }
    
    public MMPossibilityListCell(Possibility p) {
        this();
        knownChars.setText(p.letters());
        String elimStr = "<html>";
        for (char c = 'A'; c <= 'Z'; c++) {
            if (p.getNoMore(c)) {
                elimStr += "<strike>"+c+"</strike>";
            }
            else {
                elimStr += c;
            }
        }
        elimStr += "</html>";
        elimChars.setText(elimStr);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        knownChars = new javax.swing.JLabel();
        elimChars = new javax.swing.JLabel();

        knownChars.setText("_________");

        elimChars.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        elimChars.setForeground(new java.awt.Color(153, 153, 153));
        elimChars.setText("ABCDEFGHIJKLMNOPQURSTUVWXYZ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(knownChars)
            .addComponent(elimChars)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(knownChars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elimChars))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel elimChars;
    private javax.swing.JLabel knownChars;
    // End of variables declaration//GEN-END:variables
}
